### ISSUE TITLE
Feature Req: allow a callback to be invoked after measure?

### ISSUE THREAD

**Issue by jchip** [hapijs/heavy#14]
This would be useful to allow adding a custom callback to do things like monitoring/log every time a new sample is measured.

**Comment by Marsup** [comment]
An event emitter you mean ?

**Comment by jchip** [comment]
yeah, that'd be even better.

**Comment by hueniverse** [comment]
Bad idea. You don't want to add load as part of measuring load. I suggest you write separate logic that runs less frequent and logs information.

**Comment by jchip** [comment]
Of course.  I want to keep a running average of event loop latency and report into a dashboard metric once per minute.  The reporting logic runs separately. I was going to do a simple setTimeout also but seeing that Hapi (which we are using) already have this I thought we could tap into it rather than running another event loop latency measurement.

**Comment by hueniverse** [comment]
A better solution is to have the hapi server expose the calculations as a public interface. Since you know the interval frequency, you can set your own timer to check on the values and use them.
