### ISSUE TITLE
Heavy constructor doesn't apply defaults properly

### ISSUE THREAD

**Issue by YouriT** [hapijs/heavy#17]
In `lib/index.js` line 44
I believe that
```
this.settings = Hoek.applyToDefaults(internals.defaults, options);
```
should in fact be:
```
this.settings = Hoek.applyToDefaults(internals.defaults.process, options);
```

No big deal but was confusing when trying to understand the logic of the module.

Correct me if I'm wrong. Otherwise I can make a quick PR if you'd like.

**Comment by hueniverse** [comment]
Yep, that's a bug. I'll take a PR.

**Comment by hueniverse** [comment]
No longer an issue in v5.
