### ISSUE TITLE
Recommended settings?

### ISSUE THREAD

**Issue by DiegoRBaquero** [hapijs/heavy#38]
#### Support plan

* *which support plan is this issue covered by?* (e.g. Community, Core, Plus, or Enterprise): community
* *is this issue currently blocking your project?* (yes/no): no
* *is this issue affecting a production system?* (yes/no): kinda

#### Context

* *node version*: 12
* *module version*: latest
* *environment* (e.g. node, browser, native): node
* *used with* (e.g. hapi application, another framework, standalone, ...): hapi app
* *any other relevant information*:

#### How can we help?

What's a recommended setting for max event loop delay and sampling interval?

Also, if answered I can PR to include an explanation in the docs :)

Thank you!

**Comment by hueniverse** [comment]
There are no recommended settings. This is very much application specific based on how long you expect your endpoints to take and if they perform a lot of sync operations.
