### ISSUE TITLE
Disabling memory measurement when not used

### ISSUE THREAD

**Issue by DiegoRBaquero** [hapijs/heavy#39]
#### Support plan

* *which support plan is this issue covered by?* (e.g. Community, Core, Plus, or Enterprise): Community
* *is this issue currently blocking your project?* (yes/no): no
* *is this issue affecting a production system?* (yes/no): no

#### Context

* *node version*:  12
* *module version*: latest
* *environment* (e.g. node, browser, native):  node
* *used with* (e.g. hapi application, another framework, standalone, ...): hapi app
* *any other relevant information*:

#### What problem are you trying to solve?

Reduce CPU usage

#### Do you have a new or modified API suggestion to solve the problem?

Don't poll memory usage if disabled

**Comment by kanongil** [comment]
Do you have any measurements that show that this is an actual issue? And that it will help?

**Comment by DiegoRBaquero** [comment]
We run over 100 kubernetes pods per env and use a low sampling value, so even even if only affecting idle cpu usage by 0.1%, the whole cluster could see an improvement.

Also, running local tests, running on a 100ms interval `process.memoryUsage()` increases event loop latency by 0.1 - 0.4ms.

I know this is a micro optimization but at scale it's greatly appreciated.
